=== amineamanzou/MIAGE-Java-Project/M1APP-XML-Videotheque/src/formation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:element name='formation'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='intitule'/>
          <xs:element ref='matieres'/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name='matieres'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='matiere' maxOccurs='unbounded'/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name='matiere'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='intitule'/>
          <xs:element ref='horaire'/>
          <xs:element ref='equipe'/>
         </xs:sequence>
        <xs:attribute name='code' type='xs:string' use='required'/>
      </xs:complexType>
   </xs:element>

   <xs:element name='intitule' type='xs:string'/>

   <xs:element name='horaire'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='cm'/>
          <xs:element ref='td'/>
          <xs:element ref='tp'/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name='cm' type='xs:integer'/>
   <xs:element name='td' type='xs:integer'/>
   <xs:element name='tp' type='xs:integer'/>

   <xs:element name='equipe'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='membre' maxOccurs='unbounded'/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name='membre'>
      <xs:complexType>
         <xs:sequence>
          <xs:element ref='nom'/>
          <xs:element ref='prenom'/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:element name='nom' type='xs:string'/>
   <xs:element name='prenom' type='xs:string'/>

</xs:schema>

=== amineamanzou/MIAGE-Java-Project/M1APP-XML-Videotheque/src/formation.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<formation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="formation.xsd">

    <intitule>MIAGE</intitule>
    <matieres>
        <matiere code="INF1">
            <intitule>WEB BDD</intitule>
            <horaire>
                <cm>4</cm>
                <td>9</td>
                <tp>9</tp>
            </horaire>
            <equipe>
                <membre>
                    <nom>Raul</nom>
                    <prenom>Mazo</prenom>
                </membre>
                <membre>
                    <nom>Jean</nom>
                    <prenom>Neymare</prenom>
                </membre>
            </equipe>
        </matiere>
        <matiere code="INF2">
            <intitule>Developpement</intitule>
            <horaire>
                <cm>6</cm>
                <td>10</td>
                <tp>5</tp>
            </horaire>
            <equipe>
                <membre>
                    <nom>Jian</nom>
                    <prenom>Lee</prenom>
                </membre>
                <membre>
                    <nom>Jean</nom>
                    <prenom>Neymare</prenom>
                </membre>
            </equipe>
        </matiere>
        <matiere code="INF3">
            <intitule>Java</intitule>
            <horaire>
                <cm>30</cm>
                <td>4</td>
                <tp>10</tp>
            </horaire>
            <equipe>
                <membre>
                    <nom>Hug</nom>
                    <prenom>Charlotte</prenom>
                </membre>
                <membre>
                    <nom>Deneckere</nom>
                    <prenom>Rebecca</prenom>
                </membre>
            </equipe>
        </matiere>
    </matieres>
</formation>
